table DimPuntoVenta
	lineageTag: 4007dea7-e5b2-4872-85f9-3a249a6db498

	column PuntoVenta
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 69d3e318-a854-4ec6-8839-2f215bb2fdbf
		isDefaultLabel
		summarizeBy: none
		sourceColumn: PuntoVenta

		annotation SummarizationSetBy = Automatic

	column IdSucursal
		dataType: string
		lineageTag: 97530b2e-0caf-4256-8714-1f5f3d9ef1c3
		summarizeBy: none
		sourceColumn: IdSucursal

		annotation SummarizationSetBy = Automatic

	partition DimPuntoVenta = m
		mode: import
		queryGroup: 'Dimension Tables'
		source =
				let
				    Source = Excel.Workbook(File.Contents(Text.Combine({SourceFolder, "\puntos-de-venta.xlsx"})), null, true),
				    Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"PuntoVenta", Int64.Type}, {"IdSucursal", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

