table FactWhatsApp
	lineageTag: 43927ec9-b192-44f5-8190-8a74304e5309

	measure 'Contactos (Diario)' = ```
			
			SUMX (
			    VALUES ( DimFuente[IdFuente] ),
			    VAR UltimaFechaPorFuente =
			        CALCULATE (
			            MAX ( FactWhatsApp[Fecha] )
			        )
			    RETURN
			        CALCULATE (
			            SUM ( FactWhatsApp[Contactos] ),
			            FactWhatsApp[Fecha] = UltimaFechaPorFuente
			        )
			)
			
			```
		formatString: #,0
		lineageTag: 55aa1222-0ffd-4c09-9376-95e68931a9d6

	measure 'SeguidoresCanal (Diario)' = ```
			
			SUMX (
			    VALUES ( DimFuente[IdFuente] ),
			    VAR UltimaFechaPorFuente =
			        CALCULATE (
			            MAX ( FactWhatsApp[Fecha] )
			        )
			    RETURN
			        CALCULATE (
			            SUM ( FactWhatsApp[SeguidoresCanal] ),
			            FactWhatsApp[Fecha] = UltimaFechaPorFuente
			        )
			)
			
			```
		formatString: #,0
		lineageTag: 1c7121ad-1934-4b6c-8dfe-7ecd09c4d2df

	measure CrecimientoAcumuladoContactos = ```
			
			VAR FechaEje =
			    MAX ( DimCalendario[Fecha] )
			VAR FechaInicioSlicer =
			    CALCULATE (
			        MIN ( DimCalendario[Fecha] ),
			        ALLSELECTED ( DimCalendario )
			    )
			VAR ValorBase =
			    CALCULATE (
			        SUM ( FactWhatsApp[Contactos] ),
			        TOPN (
			            1,
			            FILTER (
			                ALL ( DimCalendario ),
			                DimCalendario[Fecha] <= FechaInicioSlicer
			                    && NOT ISBLANK (
			                        CALCULATE (
			                            SUM ( FactWhatsApp[Contactos] )
			                        )
			                    )
			            ),
			            DimCalendario[Fecha], DESC
			        )
			    )
			VAR UltimaFechaConDatos =
			    CALCULATE (
			        MAX ( FactWhatsApp[Fecha] ),
			        FILTER (
			            ALL ( DimCalendario ),
			            DimCalendario[Fecha] <= FechaEje
			                && NOT ISBLANK (
			                    CALCULATE (
			                        SUM ( FactWhatsApp[Contactos] )
			                    )
			                )
			        )
			    )
			VAR ValorHoy =
			    CALCULATE (
			        SUM ( FactWhatsApp[Contactos] ),
			        FILTER (
			            ALL ( DimCalendario ),
			            DimCalendario[Fecha] = UltimaFechaConDatos
			        )
			    )
			VAR Resultado = ValorHoy - ValorBase
			RETURN
			    IF (
			        ISBLANK ( UltimaFechaConDatos ),
			        0,
			        Resultado
			    )
			
			```
		formatString: 0
		lineageTag: 2c1e58a9-fff1-4a6c-bb9c-925c5f9df6e2

	measure CrecimientoAcumuladoSeguidoresCanal = ```
			
			VAR FechaEje =
			    MAX ( DimCalendario[Fecha] )
			VAR FechaInicioSlicer =
			    CALCULATE (
			        MIN ( DimCalendario[Fecha] ),
			        ALLSELECTED ( DimCalendario )
			    )
			VAR ValorBase =
			    CALCULATE (
			        SUM ( FactWhatsApp[SeguidoresCanal] ),
			        TOPN (
			            1,
			            FILTER (
			                ALL ( DimCalendario ),
			                DimCalendario[Fecha] <= FechaInicioSlicer
			                    && NOT ISBLANK (
			                        CALCULATE (
			                            SUM ( FactWhatsApp[SeguidoresCanal] )
			                        )
			                    )
			            ),
			            DimCalendario[Fecha], DESC
			        )
			    )
			VAR UltimaFechaConDatos =
			    CALCULATE (
			        MAX ( FactWhatsApp[Fecha] ),
			        FILTER (
			            ALL ( DimCalendario ),
			            DimCalendario[Fecha] <= FechaEje
			                && NOT ISBLANK (
			                    CALCULATE (
			                        SUM ( FactWhatsApp[SeguidoresCanal] )
			                    )
			                )
			        )
			    )
			VAR ValorHoy =
			    CALCULATE (
			        SUM ( FactWhatsApp[SeguidoresCanal] ),
			        FILTER (
			            ALL ( DimCalendario ),
			            DimCalendario[Fecha] = UltimaFechaConDatos
			        )
			    )
			VAR Resultado = ValorHoy - ValorBase
			RETURN
			    IF (
			        ISBLANK ( UltimaFechaConDatos ),
			        0,
			        Resultado
			    )
			
			```
		formatString: #,0
		lineageTag: d0e50e83-2fd9-4fab-b403-b54ba242fd17

	measure '% Seguidores del Canal' = ```
			
			DIVIDE (
			    [SeguidoresCanal (Diario)],
			    [Contactos (Diario)],
			    0
			)
			
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: aeca8fe2-8051-43fc-90e6-47e69226fc28

	column Fecha
		dataType: dateTime
		formatString: Short Date
		lineageTag: 983257f9-6b22-4a49-858e-443cd87f3832
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IdFuente
		dataType: string
		lineageTag: 59b70882-5e81-4d31-ae72-8a1c3b1f9313
		summarizeBy: none
		sourceColumn: IdFuente

		annotation SummarizationSetBy = Automatic

	column Contactos
		dataType: int64
		isHidden
		formatString: #,0
		lineageTag: 365d285f-50ae-48de-b5e4-34dff59eb4bf
		summarizeBy: sum
		sourceColumn: Contactos

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SeguidoresCanal
		dataType: int64
		isHidden
		formatString: #,0
		lineageTag: 493bbb20-6ad8-4d21-bd14-abecea420efc
		summarizeBy: sum
		sourceColumn: SeguidoresCanal

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition FactWhatsApp = m
		mode: import
		queryGroup: 'Fact Tables'
		source =
				let
				    Source = _FactRedesSociales,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Fecha", "IdFuente", "ContactosWA", "SeguidoresCanalWA"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns",{{"ContactosWA", "Contactos"}, {"SeguidoresCanalWA", "SeguidoresCanal"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

