table MeasuresTable
	lineageTag: f54daf9a-7d54-48c1-9680-4ce8920fed58

	measure Legend = 1
		formatString: 0
		lineageTag: 276efb4c-fbe1-4013-919f-8b102cb2b734

	measure 'Date Range Legend' = ```
			
			VAR MinDate =
			    FORMAT (
			        MIN ( DimCalendario[Fecha] ),
			        "dd/mm/yyyy"
			    )
			VAR MaxDate =
			    FORMAT (
			        MAX ( DimCalendario[Fecha] ),
			        "dd/mm/yyyy"
			    )
			RETURN
			    "Desde el " & MinDate & " Hasta el " & MaxDate
			
			```
		lineageTag: 8a167dc1-ea31-4ffc-9c72-de21990ea58d

	partition MeasuresTable = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

